name: Build and Deploy to ECR

on:
  push:
    branches:
      - master  # Ejecutar cuando se haga push en la rama 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev 
    steps:
    # 1. Configurar el repositorio
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    # 2. Autenticarse en AWS ECR
    - name: Log in to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
   
    # 3. Configurar variables
    - name: Set up environment variables
      run: echo "IMAGE_NAME=dev/my_app" >> $GITHUB_ENV

    # 4. Construir la imagen Docker
    - name : Build & Push Docker image
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ env.IMAGE_NAME }}
        IMAGE_NAME: ${{ steps.login-ecr.outputs.registry }}/${{ env.IMAGE_NAME }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $IMAGE_NAME:$IMAGE_TAG .
        docker push $IMAGE_NAME:$IMAGE_TAG






